<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RequestGuardMcp.Core\RequestGuardMcp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="MaxMind.GeoIP2" />
    <PackageReference Include="MaxMind.Db" />
  </ItemGroup>

</Project>
